spring:
  data:
    solr:
      host: http://192.168.56.129:8080/solr
  datasource:
    url: jdbc:mysql://localhost:3306/v7?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10

dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181
  protocol:
    port: 28811
