
dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181
  protocol:
    port: 28816

spring:
  redis:
    host: 192.168.56.129
    port: 6379
    password: java1907

server:
  port: 8087

