dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181
  protocol:
    port: 28810

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v7?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 7770

pagehelper:
  helper-dialect: mysql
  reasonable: true
