dubbo:
  application:
    name: web-cart
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181

server:
  port: 9097

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.129
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907

