dubbo:
  application:
    name: web-order
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181

server:
  port: 9098

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.129
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907

alipay:
  serverUrl: https://openapi.alipaydev.com/gateway.do
  appid: 2021000121614288
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpj5nyPEsIdzUP/L7SJSu+0KXTfSH7GjKcv0GBDJy6+I7BKoePSPovBdOvlcAQjPD6BZY02NF8L0q19p6M/6XCkrjOQLWoY2mHJ0/IAY5Iyfbl9yjefrJj7UuXvVrfYc8+r7IsqzgCEWoqmxG5H+NocIovGgTYFpJiplydM9M03qB9p7oyRweepBGVS6wmDcJdmFTJJjxRVbduVg8kSwF9D1T9BCvHzSrbVOwb/CMmSOatMYk3xCJ7DAfsmcJxh/zbVZbSYzH+loXwi/nmelx2iXmyoqsIH0Myu7UWPPJEus9oAgkf3+dLDPALn8e3i9KZ4ziPWf8npnKbxiGOcyobAgMBAAECggEADWuLMKvq+GGO9pP3emRswO58oW9++APLy7Ireg5IfVfc3JcEIagR/RTF+1ir2eN90xwMFmSut9h6XkqFo/073lmEfPaMKiasHIFVBCxzWXl6rBrSxkFa1yPZ3smi3pk8MObxAC4RAcDlGTgqv+8xLXvyw+WYSo4Gyf4GyH5okf+HcwCvXs0gqPt9SjhB/u8Qk+Gr+Xb5RAkoYr3Y1hZpv/QPc/o4p61cwDM1kXnOj9cMfbdG9zBqQJofvhSWJYTdEvA3dLDk8Xyod5V9H5jhs4k57zkI1548yO86brUb4qv84A+okvgogJL+T6APBSbXlrfYrR7ZFxXM8a0mX9bDOQKBgQDyTfl8jPGn3WsDaUE/tIwDaG4h/8T1RnHm39QIYypOCLpKMpcs1Sux1Xz4QFWa+JCLDyaOdbl7JQGbTnK3T5s5hdAW7Sj5vN6RllP1Z6ZwiMl0+Xe6yemR6dlmMkoMBP5OV9S8+269NICr/sG9fluUop1al9NDRBsLCv0euRqjlwKBgQCzJRAXeJgT/Z/+o8vU902Np9CHbBprEhMf368biSXXg6QvqAq/+hUWodqhDqoIw3rYpJ5RQLcGo1wv5u8D6+5QJrgqtvcdvBZSaNRvcQ7JT5LWD7yHrb8GdiQg5UEx+BSTBpNt3p5/YqCnnc1gMB00Q8y7hPMOUEby6wyfrnKuHQKBgAXKMzH0tDmMouf79eEt0UKrliYd1Hj/6+zWYFyq8fHXZ4wqVU5u8ZJYRZow/1qqodmQzR0OVxZINhed8kPLFSx0tBo4JIiDKNZVvz/X8DQ0MIwpAeFmvbwM2HMGtJpA7Eq28pBpeaXvwTta5QpAILQWhqgJhLTQxcynwJChX6+VAoGAQ5lmuxScfl6kMxhn4BL5xsxeWdunFGQbp1lm4EMebnaUTA9jDxI1RvcIYuH/s5LgFkP4Ib0D05NtQ/4mjxpGMSSLNkMYeLXyzmIUV4EYDUrjo7cIc0JS5QNLmsYnlc2BJgHDPCBXOsZizR001GkTfBdheBkxBmOwghXEC7VuPNkCgYEArDwlkco0UaygJ2SS+RO/rADPUjjBMWMwOPUWePBDGHNGj/mrlKJgqwfawwxcDW138pBU99WnCejq6Ga9zLErWK6QU/0IhW/IgZl1XrfgdZRQdvrd7ggyl8xTASsfFUQVhkMmAFoet3UqxlNAp/ltUN/6WxlhVN50fqmVhdrkqVI=
  format: json
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjGO0W5GL3F82wEijzZ3rzDHRS+6oj6djYuc9Xd0sBBJQtrnUv3mihUkKwms94bcOYjK8ivkPesQ9+kmNQB918mfk+LzOQwGJa19eKPPhydM9a7jKN6fJ5Of1d2D6BN4YlldpD01QJFc20zC3iqqrlbbQoJ6I88vGKvXCZ0Ny8IgeiMogHStug/L0EsqsQPWTPsdO2lxzvjbAcKosnOt0mUzvmWWqz9hDv7iX82JrMDK0U8d5rTyrKRuo9cS/jzTnhYxcTEGzDU4gF+W/AhhLt7MAvYY6qvEidsPJhB6MdozsqbcwNE4mA9CMax1fhwFZCHW1OOo0Pm9oy5aAllq6EwIDAQAB
  signType: RSA2
