dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 192.168.56.129:2181

server:
  port: 9090
spring:
  thymeleaf:
    cache: false

#上传文件
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  # 缩略图生成
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.56.129:22122

image:
  server: http://192.168.56.129/